name: "Security Pipeline (Python: SAST)"

on:
  push:

permissions:
  contents: write   # important pour gh-pages
  pages: write
  id-token: write
  security-events: write
  actions: read

jobs:
  security_scan:
    name: Analyse SAST + Rapport Allure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Initialisation de CodeQL
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      # Analyse CodeQL
      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"

      # Préparer un résultat pour Allure
      - name: Préparer rapport Allure
        run: |
          mkdir -p build/allure-results
          echo '{"status":"passed","name":"CodeQL Analysis","message":"Voir l’onglet Security pour les résultats détaillés."}' \
          > build/allure-results/codeql-result.json

      # Génération du rapport Allure
      - name: Générer rapport Allure
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      # Publication du rapport sur GitHub Pages
      - name: Publier rapport Allure
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
