name: "Security Pipeline (Python: SAST + SCA + Image + DAST)"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull_code:
    name: Pulling du code
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  sast:
    name: Analyse statique (CodeQL)
    runs-on: self-hosted
    needs: pull_code
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
      - name: Export CodeQL SARIF
        run: |
          mkdir -p reports
          # CodeQL action a déjà uploadé le SARIF, on récupère une copie locale depuis le dossier par défaut si présent
          # En fallback, on génère un "marqueur" pour Allure
          echo '{"note":"CodeQL executed; see Security tab for full SARIF"}' > reports/codeql-summary.json
      - name: Upload CodeQL report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-report
          path: reports/

