name: "SAST - CodeQL Analysis with Allure"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  security-events: write
  pages: write
  id-token: write

jobs:
  codeql:
    name: Analyse SAST (CodeQL)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
          output: results

      - name: Upload CodeQL SARIF
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif
          path: results

  allure:
    name: Génération du rapport Allure
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download CodeQL SARIF results
        uses: actions/download-artifact@v4
        with:
          name: codeql-sarif
          path: reports

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre unzip wget python3 python3-pip
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.zip
          unzip allure-2.25.0.zip -d /opt/
          sudo ln -s /opt/allure-2.25.0/bin/allure /usr/bin/allure
          pip3 install jsonschema

      - name: Convert CodeQL SARIF to Allure
        run: |
          mkdir -p allure-results
          python3 scripts/convert_codeql.py reports allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    name: Publier Allure Report sur GitHub Pages
    runs-on: ubuntu-latest
    needs: allure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
